# Generated by Django 2.1.7 on 2019-02-13 05:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('num_max_students', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_identification_string', models.AutoField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.SchoolsModel')),
            ],
        ),
    ]
