# Generated by Django 2.1.7 on 2019-02-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_ID',
            new_name='student_id',
        ),
    ]
